# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17waCK7d2IVFmvNL6izWCVVuf6qxMaVgb
"""
import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

# =========================================================
# FUNGSI CUBIC SPLINE MANUAL (NATURAL SPLINE)
# =========================================================
def cubic_spline_manual(x, y, x_pred):
    n = len(x) - 1
    h = np.diff(x)

    # Sistem persamaan untuk koefisien c
    A = np.zeros((n + 1, n + 1))
    B = np.zeros(n + 1)

    A[0, 0] = 1
    A[n, n] = 1

    for i in range(1, n):
        A[i, i-1] = h[i-1]
        A[i, i]   = 2 * (h[i-1] + h[i])
        A[i, i+1] = h[i]
        B[i] = 3 * ((y[i+1]-y[i])/h[i] - (y[i]-y[i-1])/h[i-1])

    c = np.linalg.solve(A, B)

    a = y[:-1]
    b = np.zeros(n)
    d = np.zeros(n)

    for i in range(n):
        b[i] = (y[i+1]-y[i])/h[i] - h[i]*(2*c[i]+c[i+1])/3
        d[i] = (c[i+1]-c[i])/(3*h[i])

    for i in range(n):
        if x[i] <= x_pred <= x[i+1]:
            dx = x_pred - x[i]
            return a[i] + b[i]*dx + c[i]*dx**2 + d[i]*dx**3

    return None

# =========================================================
# KONFIGURASI HALAMAN
# =========================================================
st.set_page_config(
    page_title="Interpolasi Kubik Spline",
    page_icon="🌸",
    layout="centered"
)

# =========================================================
# CSS CUSTOM (ESTETIK + AKADEMIK)
# =========================================================
st.markdown("""
<style>
body {
    background-color: #fff0f6;
}
.block-container {
    padding: 30px;
}
.card {
    background: white;
    padding: 25px;
    border-radius: 20px;
    box-shadow: 0px 10px 30px rgba(255,105,180,0.25);
    margin-bottom: 25px;
}
h1 {
    color: #ff5fa2;
}
h2, h3 {
    color: #d63384;
}
.stButton>button {
    background: linear-gradient(90deg, #ff85c0, #ff5fa2);
    color: white;
    border-radius: 14px;
    font-weight: bold;
    padding: 10px 28px;
}
.stButton>button:hover {
    transform: scale(1.04);
}
</style>
""", unsafe_allow_html=True)

# =========================================================
# HEADER
# =========================================================
st.markdown(
    """
    <div style="text-align:center;">
        <h1>🌸 Interpolasi Kubik Spline 🌸</h1>
        <p style="font-size:18px; color:#c2185b;">
            Haii! Selamat datang di website interpolasi 💗<br>
            Masukkan nama variabel dan data X & Y kamu yaa ✨
        </p>
    </div>
    """,
    unsafe_allow_html=True
)
# =========================================================
# PENJELASAN ALGORITMA (INTERAKTIF)
# =========================================================
with st.expander("📘 Lihat Algoritma Cubic Spline (Klik untuk membuka)"):
    st.markdown("""
### 📌 Algoritma Interpolasi Kubik Spline (Natural)

**1. Persamaan Umum Cubic Spline**  
\[
f_i(x) = a_i + b_i(x-x_i) + c_i(x-x_i)^2 + d_i(x-x_i)^3
\]

**2. Menghitung Jarak Antar Titik**  
\[
h_i = x_{i+1} - x_i
\]

**3. Syarat Interpolasi**  
Spline harus melalui seluruh titik data:
\[
f_i(x_i)=y_i,\quad f_i(x_{i+1})=y_{i+1}
\]

**4. Kekontinuan Turunan**  
Turunan pertama dan kedua kontinu pada setiap titik.

**5. Natural Spline**  
\[
f''(x_0)=0,\quad f''(x_n)=0
\]

**6. Sistem Persamaan Linear**  
Digunakan untuk menentukan koefisien \(c_i\).

**7. Perhitungan Koefisien**  
\[
a_i,\; b_i,\; c_i,\; d_i
\]

**8. Evaluasi Spline**  
Nilai spline dihitung pada \(x\) tertentu di selang terkait.

✔️ Algoritma ini **sepenuhnya manual** dan sesuai literatur numerik.
""")

# =========================================================
# INPUT DATA
# =========================================================
st.markdown("<div class='card'>", unsafe_allow_html=True)
st.subheader("💗 Masukkan Data Anda")

x_name = st.text_input("Nama Variabel X", placeholder="contoh: Hari")
x_str  = st.text_input("Data X (pisahkan koma)", placeholder="1, 2, 4, 7")

y_name = st.text_input("Nama Variabel Y", placeholder="contoh: Tinggi Jagung (cm)")
y_str  = st.text_input("Data Y (pisahkan koma)", placeholder="10, 15, 14, 20")

x_pred = st.number_input("Nilai X yang ingin diprediksi")

st.markdown("</div>", unsafe_allow_html=True)

# =========================================================
# PROSES
# =========================================================
if st.button("💖 Hitung Interpolasi"):
    try:
        x = np.array([float(i) for i in x_str.split(",")])
        y = np.array([float(i) for i in y_str.split(",")])
    except:
        st.error("❌ Data harus berupa angka dan dipisahkan koma")
        st.stop()

    if len(x) != len(y) or len(x) < 3:
        st.error("❌ Minimal 3 titik data dan jumlah X = Y")
        st.stop()

    idx = np.argsort(x)
    x, y = x[idx], y[idx]

    if not (x.min() <= x_pred <= x.max()):
        st.error("❌ Nilai X prediksi harus berada dalam rentang data")
        st.stop()

    y_pred = cubic_spline_manual(x, y, x_pred)

    st.markdown("<div class='card'>", unsafe_allow_html=True)
    st.success(f"💗 Hasil Prediksi: **{y_name} = {y_pred:.4f}**")

    xx = np.linspace(x.min(), x.max(), 300)
    yy = [cubic_spline_manual(x, y, xi) for xi in xx]

    # VISUALISASI
    xx = np.linspace(x.min(), x.max(), 300)
    yy = [cubic_spline_manual(x, y, xi) for xi in xx]

    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot(xx, yy, linewidth=2, color="#ff5fa2", label="Kurva Cubic Spline")
    ax.scatter(x, y, color="#c2185b", label="Data Asli")
    ax.scatter(x_pred, y_pred, color="#007bff", s=80,
               label=f"Prediksi ({x_pred})")

    ax.set_xlabel(x_name, fontsize=11, color="#c2185b")
    ax.set_ylabel(y_name, fontsize=11, color="#c2185b")

    ax.grid(True, alpha=0.3)
    ax.legend()
    st.pyplot(fig)
    
    # PENUTUP
    st.markdown(
        """
        <div style="text-align:center; font-size:17px; color:#d63384; margin-top:20px;">
            Terima kasih sudah mampir 💗<br>
            Semoga hasil interpolasimu memuaskan 🎀
        </div>
        """,
        unsafe_allow_html=True
    )


# =========================================================
# FOOTER
# =========================================================
st.markdown("""
<p style="text-align:center; color:#c94f7c;">
Dibuat oleh <b>Bunga, Aira, dan Uti</b> 💗
</p>
""", unsafe_allow_html=True)
