# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17waCK7d2IVFmvNL6izWCVVuf6qxMaVgb
"""
import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

# =========================================================
# FUNGSI NATURAL CUBIC SPLINE (MANUAL)
# =========================================================
def cubic_spline_manual(x, y, x_pred):
    n = len(x) - 1
    h = np.diff(x)

    A = np.zeros((n + 1, n + 1))
    B = np.zeros(n + 1)

    A[0, 0] = 1
    A[n, n] = 1

    for i in range(1, n):
        A[i, i-1] = h[i-1]
        A[i, i] = 2*(h[i-1] + h[i])
        A[i, i+1] = h[i]
        B[i] = 3*((y[i+1]-y[i])/h[i] - (y[i]-y[i-1])/h[i-1])

    c = np.linalg.solve(A, B)

    a = y[:-1]
    b = np.zeros(n)
    d = np.zeros(n)

    for i in range(n):
        b[i] = (y[i+1]-y[i])/h[i] - h[i]*(2*c[i]+c[i+1])/3
        d[i] = (c[i+1]-c[i])/(3*h[i])

    for i in range(n):
        if x[i] <= x_pred <= x[i+1]:
            dx = x_pred - x[i]
            return a[i] + b[i]*dx + c[i]*dx**2 + d[i]*dx**3
    return None

# =========================================================
# KONFIGURASI HALAMAN
# =========================================================
st.set_page_config(
    page_title="Interpolasi Kubik Spline",
    page_icon="🌸",
    layout="centered"
)

# =========================================================
# CSS SOFT PINK – WEBSITE STYLE
# =========================================================
st.markdown("""
<style>
body {
    background-color: #fff7fb;
}
.block-container {
    padding: 35px;
}

.card {
    background: linear-gradient(135deg, #fff, #fff0f7);
    padding: 25px;
    border-radius: 18px;
    box-shadow: 0 8px 20px rgba(255, 105, 180, 0.15);
    margin-bottom: 25px;
}

h1 {
    color: #ff5fa2;
    text-align: center;
}

.subtitle {
    text-align: center;
    color: #c94f7c;
    font-size: 16px;
}

label {
    color: #c2185b !important;
    font-weight: 600;
}

.stButton button {
    background: linear-gradient(135deg, #ff8ec7, #ff5fa2);
    color: white;
    border-radius: 10px;
    font-weight: bold;
}
.stButton button:hover {
    background: linear-gradient(135deg, #ff5fa2, #ff8ec7);
}
</style>
""", unsafe_allow_html=True)

# =========================================================
# HEADER
# =========================================================
st.markdown("""
<div class="card">
    <h1>🌸 Interpolasi Kubik Spline 🌸</h1>
    <p class="subtitle">
            Haii! Selamat datang di website interpolasi 💗<br>
            Masukkan nama variabel dan data X & Y kamu yaa ✨
    </p>
</div>
""", unsafe_allow_html=True)

# =========================================================
# INPUT DATA
# =========================================================
st.markdown("<div class='card'>", unsafe_allow_html=True)
st.subheader("💗 Masukkan Data")

col1, col2 = st.columns(2)

with col1:
    x_name = st.text_input("🧷 Nama Variabel X", placeholder="contoh: Hari")
    x_str  = st.text_input("✨ Data X (pisahkan dengan koma)", placeholder="contoh: 1, 2, 5, 7, 10")

with col2:
    y_name = st.text_input("🧷 Nama Variabel Y", placeholder="contoh: Tinggi Jagung (cm)")
    y_str  = st.text_input("✨ Data Y (pisahkan dengan koma)", placeholder="contoh: 3, 6, 8, 11, 15")

x_pred = st.number_input("🔍 Nilai X yang ingin diprediksi", value=None, placeholder="Masukkan angka")
hitung = st.button("💖 Hitung Interpolasi")
st.markdown("</div>", unsafe_allow_html=True)

# =========================================================
# HASIL
# =========================================================
if hitung:
    try:
        x = np.array([float(i) for i in x_str.split(",")])
        y = np.array([float(i) for i in y_str.split(",")])
    except:
        st.error("Data harus berupa angka dan dipisahkan koma")
        st.stop()

    if len(x) < 3 or len(x) != len(y):
        st.error("Minimal 3 titik dan jumlah X = Y")
        st.stop()

    idx = np.argsort(x)
    x, y = x[idx], y[idx]

    if not (x.min() <= x_pred <= x.max()):
        st.error("Nilai prediksi harus berada dalam rentang data")
        st.stop()

    y_pred = cubic_spline_manual(x, y, x_pred)

    # HASIL PREDIKSI
    st.markdown(f"""
    <div class="card">
        💖 <b>Hasil Prediksi:</b><br>
        {y_name} = <b>{y_pred:.4f}</b>
    </div>
    """, unsafe_allow_html=True)

    # VISUALISASI
    st.markdown("<div class='card'>", unsafe_allow_html=True)
    st.subheader("📈 Visualisasi Interpolasi")

    xx = np.linspace(x.min(), x.max(), 300)
    yy = [cubic_spline_manual(x, y, xi) for xi in xx]

    fig, ax = plt.subplots(figsize=(7,4))
    ax.plot(xx, yy, color="#ff5fa2", linewidth=2, label="Kurva Kubik Spline")
    ax.scatter(x, y, color="#c2185b", label="Data Asli")
    ax.scatter(x_pred, y_pred, color="#007bff", s=80, label="Prediksi")

    ax.set_xlabel(x_name)
    ax.set_ylabel(y_name)
    ax.grid(alpha=0.3)
    ax.legend()
    st.pyplot(fig)

    st.markdown("</div>", unsafe_allow_html=True)

    # PENUTUP
    st.markdown(
        """
        <div style="text-align:center; font-size:17px; color:#d63384; margin-top:20px;">
            Terima kasih sudah mampir 💗<br>
            Semoga hasil interpolasimu memuaskan 🎀
        </div>
        """,
        unsafe_allow_html=True
    )

# =========================================================
# FOOTER
# =========================================================
st.markdown("<p style='text-align:center; color:#c94f7c;'>Dibuat oleh Bunga, Aira, dan Uti 💗</p>", unsafe_allow_html=True)
